export const FILTER_ACTIONS = {
  ALL: 'ALL',
  DIRECT: 'DIRECT',
  ONE_STOP: 'ONE_STOP',
  TWO_STOPS: 'TWO_STOPS',
  THREE_STOPS: 'THREE_STOPS',
  CHECK: 'CHECK',
  UNCHECK: 'UNCHECK',
  SORT_BY: 'SORT_BY',
  LOAD_DATA: 'LOAD_DATA',
  LOAD_MORE: 'LOAD_MORE',
};
